name: build from temlpate
on:
  workflow_dispatch:
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out repository SiteGenie/site-project-template
        uses: actions/checkout@v3   
        with:
          repository: SiteGenie/site-project-template
          token: ${{ secrets.REPO_TOKEN }} 
          path: "template"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."