name: process
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "6 3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: vaconsole/blog-test
          token: ${{ secrets.REPO_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
      - name: pull data
        run: |-
          rm -rf tmp
          mkdir -p tmp
          git clone --depth 1 https://SiteGenie:${{secrets.REPO_TOKEN}}@github.com/SiteGenie/site-project-template tmp
          ls -alh tmp/Publish
      - name: copy files and folders
        run: |-
          ls -alh
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
      # - name: run deploy flow
      #   run: ./src/deploy.sh
      #   env:
      #     REPO_NAME: ${{ github.event.repository.name }}