name: Build from temlpate
on:
  workflow_dispatch:
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out repository uuistudio/template-curator
        uses: actions/checkout@v3   
        with:
          repository: uuistudio/template-curator
          token: ${{ secrets.REPO_TOKEN }} 
          path: "template"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/template
          cd ${{ github.workspace }}/template
          npm i
          npm run build
      - run: echo "🍏 This job's status is ${{ job.status }}."
